### ISSUE TITLE
Memberlite Banner meta box Gutenberg compatibility

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite-elements#7]
When using Gutenberg, the TinyMCE editor teatareas fail to save the content. 

Disabling the TinyMCE editor and using a basic textarea form input properly saves and validates.

**Comment by pbrocks** [comment]
This issue is addressed in this PR: https://github.com/strangerstudios/memberlite-elements/pull/9

**Comment by ideadude** [comment]
The earlier fix simply disabled Gutenberg which we don't want.

This seems related to the Gutenberg issue here: WordPress/gutenberg#7176

Going to try to fix in WP Core.

**Comment by pbrocks** [comment]
We can use the full range of tinyMCE in the editor as long as when you publish or update you are viewing the Text tab, ie you see the html text in the editor, not WYSIWYG

[Sreencast showing how we can save in Memberlite Elements metaboxes](https://monosnap.com/file/ZQjzlnXr6okmhUhDac2vrHvoTOSy2F)

**Comment by ideadude** [comment]
If WP 5.0 doesn't include the fix for this, we will merge in this commit which fixes this https://github.com/strangerstudios/memberlite-elements/commit/29eaf4f3595c95adc50a0a1eaa67d232a3855007
